### ISSUE TITLE
Freecinc down

### ISSUE THREAD

**Issue by pretentious7** [jackdesert/freecinc#14]
503 from https://freecinc.com/

PS, your personal website seems down as well, is there any way to support this service? I've used it for a long time, and it has helped me a lot.

**Comment by djmitche** [comment]
This is actually run by me at the moment -- see https://github.com/freecinc/freecinc-issues/issues/13 for the report of this outage.

**Comment by djmitche** [comment]
(and I'll work on getting sponsorship set up over there..)
