### ISSUE TITLE
Proxy configuration for freecinc

### ISSUE THREAD

**Issue by ParinVachhani** [jackdesert/freecinc#2]
Can you help me run freecinc behind my institute proxy?
My `/etc/environment` includes the proxy variables shown below:
`http_proxy=http://proxy.iiit.ac.in:8080/
https_proxy=http://proxy.iiit.ac.in:8080/
ftp_proxy=http://proxy.iiit.ac.in:8080/
no_proxy="localhost,127.0.0.1, *iiit.ac.in"
HTTP_PROXY=http://proxy.iiit.ac.in:8080/
HTTPS_PROXY=http://proxy.iiit.ac.in:8080/
FTP_PROXY=http://proxy.iiit.ac.in:8080/
NO_PROXY="localhost,127.0.0.1, *iiit.ac.in"`

I am using Linux Mint 18 Sarah Cinnamon 64-bit. I have configured the proxy for applications using the help provided [here](http://askubuntu.com/a/151047).
So does freecinc need an extra level of configuration for running behind a proxy or am I missing something here?

**Comment by jackdesert** [comment]
Freecinc runs on port 53589. I've known others who had trouble connecting
because that port was blocked at work.

Might I refer you to the #taskwarrior group on freenode. Maybe they can
help you to configure taskwarrior with a proxy.

**Comment by ParinVachhani** [comment]
Thanks @jackdesert :)
