### ISSUE TITLE
Handshake failed.  Error in the certificate.

### ISSUE THREAD

**Issue by thanateros** [jackdesert/freecinc#6]
`task diagnostics` output:
```
task 2.5.1
   Platform: Linux

Compiler
    Version: 6.3.0 20170415
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++11

Build Features
      CMake: 3.7.2
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.5.6
 Build type: None

Configuration
       File: /home/nhxjhhh/.taskrc (found), 1979 bytes, mode 100664
       Data: /home/nhxjhhh/.task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
     Server: www.freecinc.com:53589
         CA: /home/nhxjhhh/.task/freecinc_1155befe.ca.pem, readable, 3755 bytes
      Trust: strict
Certificate: /home/nhxjhhh/.task/freecinc_1155befe.cert.pem, readable, 3741 bytes
        Key: /home/nhxjhhh/.task/freecinc_1155befe.key.pem, readable, 25367 bytes
    Ciphers: NORMAL
      Creds: FreeCinc/freecinc_1155befe/************************************

Hooks
     System: Enabled
   Location: /home/nhxjhhh/.task/hooks
             (-none-)

Tests
      $TERM: screen-256color (245x72)
       Dups: Scanned 11 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 11 tasks for broken references:
             No broken references found
```

I follow the instructions from the website to the letter; also, the diagnostic output above doesn't show any errors, all three .pem files are readable, Server and Creds are populated.

I have done this a handful of times on various systems (android, linux, windows) and I get the exact same error each time.

Huge fan of taskwarrior; would like to sync across my devices.

Before I go bang my head into a wall, I figured I would ask for help.  What am I doing wrong?

I have this on a Digital Ocean droplet currently with port 53589 open.

**Comment by jackdesert** [comment]
I don't use taskwarrior anymore. You may be able to find help in #taskwarrior on freenode.

**Comment by thanateros** [comment]
Thanks.

I'm curious: what do you use nowadays for task tracking?

And: does that mean the freecinc service is defunct now?

**Comment by jackdesert** [comment]
> I'm curious: what do you use nowadays for task tracking?

I track tasks in vim. Meaning I have a text file in this format:

    * Get Bill to remove my old email address from his address book
    * Send Kate a printer (or model number)
    * Open Enrollment: THANKSGIVING (Technically Dec 15)
    * Call Neuro places and find out which ones take self pay and what the cost is
    * Taxes Monday
    * Kick ASS on that horn

I `scp` this file to a server, where it is parsed by a webserver and viewable by my work cohorts as colored html. But it's sooooo easy to edit.

> And: does that mean the freecinc service is defunct now?

Freecinc is still up and running, and apparently working for most folks (I think!) But I get an email or two a month from someone who can't perform an initial sync. 

Freecinc is free software. Ideally someone will step up who wants to take over management of the site, or create a separate site using the same software.

**Comment by jackdesert** [comment]
You piqued my curiosity. I just installed taskwarrior 2.5.1 on my machine via `apt-get`, followed the instructions on freecinc.com to set up new keys, added one task, and performed inital sync. Like I said, "works for me", but people still write in occasionally to say it's not working for them. 

And there's still a bot running in the amazon cloud that syncs with freecinc every minute (See source code at https://github.com/jackdesert/freecinc/blob/master/tools/restart_unless_sync.go ). If that sync fails twice in a row, it sends me an email and asks freecinc to restart the taskd service. 

And when it goes down for any length of time, I get emails from real people. Which leads me to believe it's still up and running. But if someone wants to help out I'm ready to pass the reigns.

**Comment by non-Jedi** [comment]
Fwiw, I've been seeing the same issue for the past 24 hours. I'll probably take it as an opportunity to finally setup my own server to host though.

**Comment by thanateros** [comment]
Thanks for the insight into an alternative organizational work flow.

And thanks for verifying everything on the remote end; now I know for sure that I need to investigate my end.  Maybe I have ufw issues.

Thanks again!
