### ISSUE TITLE
Sync failed.  The Taskserver returned error: 504 Request too big

### ISSUE THREAD

**Issue by engines-wafu** [jackdesert/freecinc#7]
Just ran into this on initial sync.  Can you temporarily increase the limit?

**Comment by engines-wafu** [comment]
I think the command below in /var/taskd/config should work:

`request.limit 0`

**Comment by jackdesert** [comment]
This is the first time I've seen this issue. Do you know how big your data file is? The default appears to be 1MB

**Comment by engines-wafu** [comment]
I don't know how big the file is, but I did have this exact problem when
setting up taskd on a raspberry pi.

**Comment by jackdesert** [comment]
@gavinedwards will you run these commands and paste the output here?

    cd ~/.task
    ls -alh

Also, did you eventually get it syncing with your raspberry pi?

**Comment by engines-wafu** [comment]
total 25096
drwxr-xr-x   29 gavin  staff   928B May 29 19:56 ./
drwxr-xr-x+ 188 gavin  staff   5.9K Jun  1 11:56 ../
-rw-rw-r--    1 gavin  staff   231B Mar  2 06:17 .vim_tw.history
drwxrwxr-x    5 gavin  staff   160B Apr  9  2017
Taskwarrior-habitica-hooks-master/
-rw-r--r--    1 gavin  staff   709B May 29 20:16 backlog.data
-rw-------    1 gavin  staff   1.9K Apr  7 18:52 ca.cert.pem
-rw-r--r--    1 gavin  staff   959K May 29 20:15 completed.data
-rw-r--r--@   1 gavin  staff   2.0K May 29 19:56 ####.ca.pem
-rw-r--r--@   1 gavin  staff   2.0K May 29 19:56 ####.cert.pem
-rw-r--r--@   1 gavin  staff    11K May 29 19:56 ####.key.pem
-rw-------    1 gavin  staff   1.9K Apr  7 18:52 ####.cert.pem
-rw-------    1 gavin  staff    11K Apr  7 18:52 ####.key.pem
drwxr-xr-x    9 gavin  staff   288B Feb 13 22:08 hooks/
-rw-r--r--    1 gavin  staff   8.1K May 29 20:16 pending.data
-rw-r--r--    1 gavin  staff   148K May 29 20:16 sync_hook.log
-rw-rw-r--    1 gavin  staff   1.0M Apr  6 18:09 task-backup-20180406.tar.gz
-rw-r--r--    1 gavin  staff   2.0K Apr 17  2017 task.2fdaa844.task
-rw-r--r--    1 gavin  staff   2.0K Apr 18  2017 task.6ccd1ea6.task
-rw-r--r--    1 gavin  staff   1.9K Apr 12  2017 task.7abff96b.task
-rw-r--r--    1 gavin  staff   2.0K May  1  2017 task.7dce9cf2.task
-rw-rw-r--    1 gavin  staff   2.1K Apr  2 01:03 task.7e7958c6.task
-rw-rw-r--    1 gavin  staff   2.0K Jun  8  2017 task.995e03ac.task
-rw-rw-r--    1 gavin  staff   1.9K Sep 11  2017 task.b39318d8.task
-rw-r--r--    1 gavin  staff   2.0K Apr 18  2017 task.bb51876c.task
-rw-rw-r--    1 gavin  staff   2.0K Oct 21  2017 task.c02b449c.task
-rw-rw-r--    1 gavin  staff   2.0K May 15  2017 task.f4cdf417.task
lrwxrwxr-x    1 gavin  staff     7B May 28 19:07 taskrc@ -> .taskrc
lrwxrwxr-x    1 gavin  staff    48B May 28 19:05 taskwarrior@ ->
/Users/gavin/code/pomodoro-warriors/taskwarrior/
-rw-r--r--    1 gavin  staff   9.2M May 29 20:16 undo.data

It all worked on the raspberry pi once I removed the limit.


Regards,

Gavin

Gavin Edwards BEng(Hons) MSc CEng CMgr MIET MCMI

Mobile: +1 571 599 9517 | email: edwards.gavin@gmail.com

**Comment by jackdesert** [comment]
I've temporarily increased the limit to 2.9MB. Give it another shot and let me know how it goes.

**Comment by engines-wafu** [comment]
Seems like it's working fine now.  Thanks for the help!

Regards,

Gavin

Gavin Edwards BEng(Hons) MSc CEng CMgr MIET MCMI

Mobile: +1 571 599 9517 | email: edwards.gavin@gmail.com

**Comment by jackdesert** [comment]
Good to hear! Reducing limit to default of 1MB.
