### ISSUE TITLE
Server down? 

### ISSUE THREAD

**Issue by nemanjan00** [jackdesert/freecinc#8]
```
Syncing with freecinc.com:53589

Handshake failed.  Error in the pull function.
Sync failed.  Could not connect to the Taskserver.
```

After using it for quite a bit, it just stopped without me changing anything on my end.

**Comment by ariel17ml** [comment]
+1 Same issue here.

**Comment by lordcirth** [comment]
Back up for me now.

**Comment by nemanjan00** [comment]
For me also.

**Comment by jackdesert** [comment]
If taskd is down you can open https://freecinc.com/restart/jeremy in a browser to restart it.
