### ISSUE TITLE
Certificate issues on freecinc.com

### ISSUE THREAD

**Issue by mtreca** [jackdesert/freecinc#9]
Just a heads up, it seems that the certificate on freecinc.com has expired:

```
freecinc.com uses an invalid security certificate.

The certificate expired on July 15, 2018, 1:59:59 AM GMT+2. The current time is July 18, 2018, 9:49 PM. 

Error code: SEC_ERROR_EXPIRED_CERTIFICATE
```

Thanks a lot for managing this project by the way.

**Comment by djmitche** [comment]
I just fixed this.  @jackdesert do you want to close this up?  And maybe add me as a collaborator on this repo?  I will set up a dedicated org when I move the service to GKE, so I think it's best to leave this here for now.
